name: Python application

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: prepare the dataset
      run: |
        mkdir -p build && wget https://research.nhgri.nih.gov/microarray/Supplement/Images/supplemental_data -O build/supplemental_data.txt
    - name: Run experiments
      run: |
        python experiment.py